### ISSUE TITLE
guys could you upload a .zip containing the vst file?

### ISSUE THREAD

**Issue by GeorvityLabs** [acids-ircam/rave_vst#1]
for someone who wants to test it on their DAW , it would be great if you could release a .zip file containing the vst so that we can get started with some testing in the DAW rightaway.

**Comment by caillonantoine** [comment]
Hi ! We agree that this would be super cool, and we have planned to release a pre-built version of the vst in the future when the plugin leaves the beta state ! In the meantime, you can still compile it yourself using the instructions in the README.
