### ISSUE TITLE
Unable to load downloaded VST into Ableton - untrusted application issue

### ISSUE THREAD

**Issue by therealcritiq** [acids-ircam/rave_vst#14]
1. Downloaded VST through "Actions" on Github repo
2. Moved VST into /Plug-Ins/VST3 directory
3. Rescanned plugins in Ableton. Ableton throws error that indicates that RAVE.vst is untrusted and cannot be opened

Unclear how to resolve this

MacOS Version Big Sur 11.16.1
Ableton 11

**Comment by ZodiacFRA** [comment]
I think using the quarantine flag will resolve this problem, as mentioned in [this issue](https://github.com/acids-ircam/rave_vst/issues/13#issue-1235206019) and [this reddit thread](https://www.reddit.com/r/ableton/comments/galkk3/macos_catalina_10154_and_vsts_vst_cannot_be/):

`xattr -rd com.apple.quarantine <path to binary>`

**Comment by juanalonso** [comment]
No, I'm really sorry, but that does not solve the issue.
