### ISSUE TITLE
Followed instructions but no binaries available.

### ISSUE THREAD

**Issue by mirashindento** [acids-ircam/rave_vst#24]
Tried to follow your instructions:

**- Go to the "Actions" panel of this repository:** OK
**- Select the last run:** OK, but then I only got logs and no links to download the binaries...
- Download the binaries for your OS: ↑

Am I missing something...?

**Comment by ZodiacFRA** [comment]
the last build failed, use this one instead: https://github.com/acids-ircam/rave_vst/actions/runs/2320252841

**Comment by mirashindento** [comment]
Thanks, but I just can see where to dl the binary file :-/
