### ISSUE TITLE
starting build on osx

### ISSUE THREAD

**Issue by deccolquitt** [acids-ircam/rave_vst#6]
Hi, I'm not particularly well versed in coding at all, and I can't seem to get the VST started...

`sudo dnf update ; sudo dnf install git cmake g++ libX11-devel libXrandr-devel libXinerama-devel libXcursor-devel freetype-devel libcurl-devel alsa-lib-devel`

returns

`sudo: dnf: command not found 
sudo: dnf: command not found`

and

`cd {YOUR_INSTALL_FOLDER} ; git clone git@github.com:acids-ircam/rave_vst.git ; cd rave_vst`

returns

```
Cloning into 'rave_vst'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I then tried cloning the repo using `git clone https://github.com/acids-ircam/rave_vst` which worked, as did `git submodule update --init --recursive --progress` but then `cmake .. -DCMAKE_BUILD_TYPE=Release` returns `zsh: command not found: cmake`

thanks in advance.

**Comment by ZodiacFRA** [comment]
dnf is a linux package manager, you don't need any of those if you're compiling on MacOS.
You do need to install cmake however

**Comment by deccolquitt** [comment]
thanks for your quick reply. i have downloaded cmake, but am confused as to how i use the cmake program to build the vst, it is asking for source code and binaries. I have tried running it with 'rave-vst' as the source directory, but receive the following..

`CMake Error: The source "/rave_vst/CMakeLists.txt" does not match the source "/rave_vst/source/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.`

**Comment by ZodiacFRA** [comment]
from the repo root 
```mkdir build; cd build```
to create and goto the build directory

**Comment by deccolquitt** [comment]
amazing, have built. please could you tell me the command to run the vst?

**Comment by ZodiacFRA** [comment]
either you open the vst from your favourite DAW, or you run ./RAVE from the terminal in ```rave-vst/build/rave-vst-artefacts/Release/Standalone``` :)
