### ISSUE TITLE
Pre-trained models?

### ISSUE THREAD

**Issue by vvolhejn** [acids-ircam/rave_vst#7]
I'm wondering whether there are any pre-trained models available on which I could try the plugin out without training my own model. Since training a RAVE model takes a week or so, I'm looking to try out this exciting plugin without investing this much compute. Thanks!

**Comment by therealcritiq** [comment]
I'd like to plus one this request as well please

**Comment by ZodiacFRA** [comment]
The Model explorer functionality is now available with the latest build, 1 model is available so far!
You're more than welcome to submit your own models to have them included via our API :)
To do so just open an issue on this repo
