### ISSUE TITLE
Opening binary in terminal

### ISSUE THREAD

**Issue by deccolquitt** [acids-ircam/rave_vst#8]
I am trying to open the binary in the terminal in order to get report logs on crashes. After using chmod u+x to solve the permission problem, my command appears to go through, but nothing happens. Any help would be greatly appreciated as I have run out of ideas as to how to solve this and am not massively experienced. 

```
(base) declancolquitt@iMac ~ % /Users/declancolquitt/rave_vst/build/rave-vst_artefacts/Release/Standalone/RAVE.app
zsh: permission denied: /Users/declancolquitt/rave_vst/build/rave-vst_artefacts/Release/Standalone/RAVE.app

(base) declancolquitt@iMac ~ % chmod u+x /Users/declancolquitt/rave_vst/build/rave-vst_artefacts/Release/Standalone/RAVE.app

(base) declancolquitt@iMac ~ % 
```

**Comment by ZodiacFRA** [comment]
what does `` ./Users/declancolquitt/rave_vst/build/rave-vst_artefacts/Release/Standalone/RAVE.app`` do?

**Comment by deccolquitt** [comment]
`zsh: no such file or directory: ./Users/declancolquitt/rave_vst/build/rave-vst_artefacts/Release/Standalone/RAVE.app`

**Comment by caillonantoine** [comment]
You are not launching the binary file but a folder containing the binary file. You might want to try that

```bash
./build/rave-vst_artefacts/Release/Standalone/RAVE.app/Contents/MacOS/RAVE
```

**Comment by deccolquitt** [comment]
I have copied the file path directly from the RAVE.app itself though. 

`./build/rave-vst_artefacts/Release/Standalone/RAVE.app/Contents/MacOS/RAVE`

returned

`zsh: no such file or directory: ./build/rave-vst_artefacts/Release/Standalone/RAVE.app/Contents/MacOS/RAVE`

**Comment by ZodiacFRA** [comment]
Use an absolute path, you're not executing it from the right folder
